name: repasse_anou
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.3
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^3.0.0-dev.3
  bot_toast: ^4.1.3
  supabase_flutter: ^2.2.0
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  dartz: ^0.10.1
  animations: ^2.0.8
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  riverpod_annotation: ^3.0.0-dev.3
  uuid: ^4.2.2
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.8
  flutter_image_compress: ^2.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.0
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.3
  custom_lint: ^0.5.3
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 300
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300


